### ISSUE TITLE
Not working on latest version of x64dbg

### ISSUE THREAD

**Issue by winkerbie** [x64dbg/AutoExportPatches#4]
Hi, it is no longer working on the latest version

I'm debugging an EXE and patch it as I am working. Then when I restart the process within x64dbg, the patches are not restored or even saved in the patches window.

Please fix - it is a very useful plugin.

Thanks

**Comment by mrexodia** [comment]
New snapshot will be out soon with some fixes

**Comment by winkerbie** [comment]
It might be better to integrate this into x64dbg, rather than having a separate plugin? I can't imagine anyone not needing this feature

Thanks for the update

**Comment by mrexodia** [comment]
Feel free.

**Comment by winkerbie** [comment]
Normally I would like to help - but I not sure how to do that (i don't code in C), neither do I want to mess up the main code for x64dbg. 

Sorry, I hope you are still able to update the plugin. Thanks :)

**Comment by mrexodia** [comment]
Don’t worry, your code will be reviewed. Probably it’s better than not
having this feature :)
