### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by phiDelPark** [x64dbg/AutoExportPatches#5]
Thank you for made a good program.

PLUG_EXPORT void CBLOADDB(CBTYPE, PLUG_CB_LOADSAVEDB* info)
{
	auto jpatches = json_object_get(info->root, PLUGIN_NAME);
	size_t i;
	json_t* jpatch;
	patches.clear();
	**modPatches.clear(); // Fixed bug when loading patches**
	json_array_foreach(jpatches, i, jpatch)

**Comment by mrexodia** [comment]
Thanks for the fix! You can create a pull request by editing the file on the website. But I will do it later when I’m home 😊
