### ISSUE TITLE
How to Clean My Patches

### ISSUE THREAD

**Issue by tchivs** [x64dbg/AutoExportPatches#6]
After I modify the assembly code, the program does not work properly, but after I reload it, it still saves the problem I have the problem, I need to manually restore the selection in the patch. But after I reloaded, the command came back. Is it necessary to disable the plugin to cancel the patch? I am Chinese, so this is translated by Google. I don't know if you understand it.

**Comment by ghost** [comment]
Hello @tchivs

I think the problem you have can be fixed if you use the latest commit of this patch.

Don't use the v0.1 release, use the ee97f0abb1f92c12763024929abdb990cbd6b3e3 commit!

Best regards.
